import {
  BarChart3,
  Building2,
  ClipboardList,
  CalendarDays,
  BadgeDollarSign,
  ListChecks,
  Contact,
} from "lucide-react";

export const rfpStructureSteps = [
  {
    id: 1,
    number: "1",
    title: "Executive Summary",
    icon: BarChart3,
    color: "from-[#b85f4f] to-[#c77764]",
    position: "left-bottom",
    angle: 140,
  },
  {
    id: 2,
    number: "2",
    title: "Company Information",
    icon: Building2,
    color: "from-[#944bb8] to-[#b062c9]",
    position: "left-middle",
    angle: 180,
  },
  {
    id: 3,
    number: "3",
    title: "IT Services Requirements & Scope",
    icon: ClipboardList,
    color: "from-[#4f4fb6] to-[#6764c8]",
    position: "left-top",
    angle: 220,
  },
  {
    id: 4,
    number: "4",
    title: "Timeline",
    icon: CalendarDays,
    color: "from-[#4f75ad] to-[#5d88c4]",
    position: "top-center",
    angle: 270,
  },
  {
    id: 5,
    number: "5",
    title: "Budget",
    icon: BadgeDollarSign,
    color: "from-[#4daf51] to-[#65c464]",
    position: "right-top",
    angle: 320,
  },
  {
    id: 6,
    number: "6",
    title: "Bid Selection Criteria",
    icon: ListChecks,
    color: "from-[#82b548] to-[#95c957]",
    position: "right-middle",
    angle: 0,
  },
  {
    id: 7,
    number: "7",
    title: "Contact Information",
    icon: Contact,
    color: "from-[#b5973e] to-[#c8ad55]",
    position: "right-bottom",
    angle: 40,
  },
];