import { Manrope } from "next/font/google";
import "./globals.css?dsh";
import { Navbar } from "./components/layout/Navbar";
import { Footer } from "./sections/Footer";
import { ThemeWrapper } from "./components/layout/ThemeWrapper";
import { DEFAULT_THEME } from "./lib/themes";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${DEFAULT_THEME.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`${manrope.className} ${DEFAULT_THEME.className} min-h-full flex flex-col`}
        cz-shortcut-listen="true"
        suppressHydrationWarning
      >
        <ThemeWrapper>
          <Navbar />
           {children}
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
