import {
  Manrope,
  JetBrains_Mono,
  IBM_Plex_Sans,
  IBM_Plex_Mono,
  Inter,
  Bricolage_Grotesque,
} from "next/font/google";
import "./globals.css?dsh";
import { Navbar } from "./components/layout/Navbar";
import { Footer } from "./sections/Footer";
import { ThemeWrapper } from "./components/layout/ThemeWrapper";
import { DEFAULT_THEME } from "./lib/themes";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${jetbrainsMono.variable} ${ibmPlexSans.variable} ${ibmPlexMono.variable} ${inter.variable} ${bricolage.variable} ${DEFAULT_THEME.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`${DEFAULT_THEME.className} min-h-full flex flex-col`}
        cz-shortcut-listen="true"
        suppressHydrationWarning
      >
        <ThemeWrapper>
          <Navbar />
           {children}
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
